In [2]:
import numpy as np
import pandas as pd

# load data with pandas
df = pd.read_csv('cars.csv')
# print(df)

# convert a pandas dataframe to a numpy array
X = df.values[:, 1:-1]
print(type(X))
print(X.shape)
print(X)

<class 'numpy.ndarray'>
(406, 7)
[[18.0 8 307.0 ... 3504 12.0 70]
 [15.0 8 350.0 ... 3693 11.5 70]
 [18.0 8 318.0 ... 3436 11.0 70]
 ...
 [32.0 4 135.0 ... 2295 11.6 82]
 [28.0 4 120.0 ... 2625 18.6 82]
 [31.0 4 119.0 ... 2720 19.4 82]]


In [3]:
#Get first row and the second to last row

x1 = X[0, :]
x2 = X[-2, :]

print(x1)
print(x2)

# Addition

y = x1 + x2
print(y)

[18.0 8 307.0 130 3504 12.0 70]
[28.0 4 120.0 79 2625 18.6 82]
[46.0 12 427.0 209 6129 30.6 152]


In [4]:
# Get first 5 rows and last 5 rows 

m1 = X[0:5, :]
m2 = X[-5:, :]

print(m1)
print(m2)

# Subtraction
m = m1 - m2
print(m)

[[18.0 8 307.0 130 3504 12.0 70]
 [15.0 8 350.0 165 3693 11.5 70]
 [18.0 8 318.0 150 3436 11.0 70]
 [16.0 8 304.0 150 3433 12.0 70]
 [17.0 8 302.0 140 3449 10.5 70]]
[[27.0 4 140.0 86 2790 15.6 82]
 [44.0 4 97.0 52 2130 24.6 82]
 [32.0 4 135.0 84 2295 11.6 82]
 [28.0 4 120.0 79 2625 18.6 82]
 [31.0 4 119.0 82 2720 19.4 82]]
[[-9.0 4 167.0 44 714 -3.5999999999999996 -12]
 [-29.0 4 253.0 113 1563 -13.100000000000001 -12]
 [-14.0 4 183.0 66 1141 -0.5999999999999996 -12]
 [-12.0 4 184.0 71 808 -6.600000000000001 -12]
 [-14.0 4 183.0 58 729 -8.899999999999999 -12]]


In [65]:
# this is your code to get two vectors
# the first column 
c1 = X[0:406, 0:1]
#the second to last column 
c2 = X[0:406, -2:-1]

print(c1)
print()
print(c2)


[[18.0]
 [15.0]
 [18.0]
 [16.0]
 [17.0]
 [15.0]
 [14.0]
 [14.0]
 [14.0]
 [15.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [0.0]
 [15.0]
 [14.0]
 [0.0]
 [15.0]
 [14.0]
 [24.0]
 [22.0]
 [18.0]
 [21.0]
 [27.0]
 [26.0]
 [25.0]
 [24.0]
 [25.0]
 [26.0]
 [21.0]
 [10.0]
 [10.0]
 [11.0]
 [9.0]
 [27.0]
 [28.0]
 [25.0]
 [25.0]
 [0.0]
 [19.0]
 [16.0]
 [17.0]
 [19.0]
 [18.0]
 [14.0]
 [14.0]
 [14.0]
 [14.0]
 [12.0]
 [13.0]
 [13.0]
 [18.0]
 [22.0]
 [19.0]
 [18.0]
 [23.0]
 [28.0]
 [30.0]
 [30.0]
 [31.0]
 [35.0]
 [27.0]
 [26.0]
 [24.0]
 [25.0]
 [23.0]
 [20.0]
 [21.0]
 [13.0]
 [14.0]
 [15.0]
 [14.0]
 [17.0]
 [11.0]
 [13.0]
 [12.0]
 [13.0]
 [19.0]
 [15.0]
 [13.0]
 [13.0]
 [14.0]
 [18.0]
 [22.0]
 [21.0]
 [26.0]
 [22.0]
 [28.0]
 [23.0]
 [28.0]
 [27.0]
 [13.0]
 [14.0]
 [13.0]
 [14.0]
 [15.0]
 [12.0]
 [13.0]
 [13.0]
 [14.0]
 [13.0]
 [12.0]
 [13.0]
 [18.0]
 [16.0]
 [18.0]
 [18.0]
 [23.0]
 [26.0]
 [11.0]
 [12.0]
 [13.0]
 [12.0]
 [18.0]
 [20.0]
 [21.0]
 [22.0]
 [18.0]
 [19.0]
 [21.0]
 [26.0]
 [15.0]
 [16.0]
 [29.0]
 [24.0]


In [87]:
import math
# 1. addition and subtraction
print(c1+c2)
print()
print(c1-c2)

# 2. element-wise multiplication
c4 = c1*c2
print(c4)
print()

# 3. inner product
# reshape c2 
c5 = np.empty_like(c2)
c5[:] = c2
c5 = c5.reshape(1,406)
print(np.dot(c1,c5))
print()

# 4. three norms
# norm 1
print("L1 of array 1: ", np.linalg.norm(c1, 1))
print("L2 of array 2: ", np.linalg.norm(c2, 1))
print()

# norm 2
sum1 = 0
for i in c1:
    sum1 += i**2
    
print("L2 of array 1: " , math.sqrt(sum1))

sum2 = 0
for i in c2:
    sum2 += i**2
    
print("L2 of array 2: " , math.sqrt(sum2))
print()

# norm 3
print("L3 of array 1: ", np.linalg.norm(c1, np.inf))
print("L3 of array 2: ", np.linalg.norm(c2, np.inf))
print()


# 5. compute the distance between these two vectors
print("distance: {}".format(np.linalg.norm(c1-c2)))

[[30.0]
 [26.5]
 [29.0]
 [28.0]
 [27.5]
 [25.0]
 [23.0]
 [22.5]
 [24.0]
 [23.5]
 [17.5]
 [11.5]
 [11.0]
 [10.5]
 [11.0]
 [25.0]
 [22.0]
 [8.0]
 [24.5]
 [24.0]
 [39.0]
 [37.5]
 [33.5]
 [37.0]
 [41.5]
 [46.5]
 [42.5]
 [38.5]
 [42.5]
 [38.5]
 [36.0]
 [24.0]
 [25.0]
 [24.5]
 [27.5]
 [41.5]
 [43.5]
 [39.0]
 [44.0]
 [20.0]
 [32.0]
 [31.5]
 [32.5]
 [34.5]
 [33.5]
 [26.0]
 [25.5]
 [27.5]
 [27.0]
 [23.5]
 [25.0]
 [25.0]
 [31.5]
 [41.0]
 [34.0]
 [32.5]
 [37.0]
 [42.0]
 [49.5]
 [44.5]
 [50.0]
 [53.0]
 [46.0]
 [46.5]
 [39.5]
 [42.0]
 [46.5]
 [39.5]
 [37.5]
 [25.0]
 [26.0]
 [28.5]
 [27.0]
 [28.5]
 [22.0]
 [26.5]
 [25.5]
 [25.5]
 [32.5]
 [27.5]
 [27.0]
 [29.0]
 [28.0]
 [32.5]
 [40.0]
 [40.5]
 [44.0]
 [38.0]
 [45.0]
 [37.5]
 [43.0]
 [43.5]
 [26.0]
 [25.5]
 [26.0]
 [28.5]
 [27.5]
 [23.5]
 [25.0]
 [26.0]
 [28.5]
 [24.0]
 [23.0]
 [24.0]
 [34.5]
 [34.0]
 [34.0]
 [34.5]
 [39.0]
 [47.0]
 [25.0]
 [24.5]
 [26.0]
 [24.5]
 [33.0]
 [39.0]
 [40.5]
 [38.5]
 [31.5]
 [37.5]
 [35.0]
 [41.5]
 [28.0]
 [25.5]
 [48.5]
 

In [94]:
# this is your code to get two matrices: A, B
A= X[0:406, 0:3]
B= X[0:406, -3:]
print(A)
print(B)

[[18.0 8 307.0]
 [15.0 8 350.0]
 [18.0 8 318.0]
 ...
 [32.0 4 135.0]
 [28.0 4 120.0]
 [31.0 4 119.0]]
[[3504 12.0 70]
 [3693 11.5 70]
 [3436 11.0 70]
 ...
 [2295 11.6 82]
 [2625 18.6 82]
 [2720 19.4 82]]


In [96]:
# 1. addition and subtraction 
print(A+B)
print(A-B)
print()

# 2. compute the transpose of the second matrix: C = B^T, and print the shape of C
print("Shape of B: ", B.shape)
C = np.transpose(B)
print("Shape of C: ", C.shape)
# 3. compute the product between A and C, and print the result and its shape
print(np.dot(A,C).shape)
print()
# 4. compute the transpose of the first matrix: D = A^T, and print the shape of D
print("Shape of A: ", A.shape)
D = np.transpose(A)
print("Shape of D: ", D.shape)
# 5. compute the product between D and B, and print the result and its shape
print(np.dot(B,D).shape)
print()

[[3522.0 20.0 377.0]
 [3708.0 19.5 420.0]
 [3454.0 19.0 388.0]
 ...
 [2327.0 15.6 217.0]
 [2653.0 22.6 202.0]
 [2751.0 23.4 201.0]]
[[-3486.0 -4.0 237.0]
 [-3678.0 -3.5 280.0]
 [-3418.0 -3.0 248.0]
 ...
 [-2263.0 -7.6 53.0]
 [-2597.0 -14.600000000000001 38.0]
 [-2689.0 -15.399999999999999 37.0]]

Shape of B:  (406, 3)
Shape of C:  (3, 406)
(406, 406)

Shape of A:  (406, 3)
Shape of D:  (3, 406)
(406, 406)

